gcp:
  hosts:
    node-1:
      ansible_host:
      ansible_user: dancu
      new_hostname: node-1
    node-2:
      ansible_host:
      ansible_user: dancu
      new_hostname: node-2
    node-3:
      ansible_host:
      ansible_user: dancu
      new_hostname: node-3
       