gcp:
  hosts:
    node-1:
      ansible_host: node_1.dancluster.ip-ddns.com
      ansible_user: dancu
      new_hostname: node01-gcp
    node-2:
      ansible_host: node_2.dancluster.ip-ddns.com
      ansible_user: dancu
      new_hostname: node02-gcp
    node-3:
      ansible_host: node_3.dancluster.ip-ddns.com
      ansible_user: dancu
      new_hostname: node03-gcp
       