gcp:
  hosts:
    node-1:
      ansible_host: 34.63.189.72
      ansible_user: dancu
      new_hostname: node-1-gcp
    node-2:
      ansible_host: 34.31.70.103
      ansible_user: dancu
      new_hostname: node-2-gcp
    node-3:
      ansible_host: 35.192.140.141
      ansible_user: dancu
      new_hostname: node-3-gcp
       