gcp:
  hosts:
    node-1:
      ansible_host: node_1.dancluster.ip-ddns.com
      ansible_user: dancu
      new_hostname: node01-gcp
    node-2:
      ansible_host: node_2.dancluster.ip-ddns.com
      ansible_user: dancu
      new_hostname: node02-gcp
    node-3:
      ansible_host: node_3.dancluster.ip-ddns.com
      ansible_user: dancu
      new_hostname: node03-gcp

vpn:
  children:
    vpn_server:
      hosts:
        server1:
          ansible_host: 34.27.168.110
          ansible_user: dancu
          vpn_ip: 10.1.0.1
    vpn_clients:
      hosts:
        server2:
          ansible_host: 34.31.70.103
          ansible_user: dancu
          vpn_ip: 10.1.0.2
        server3:
          ansible_host: 35.192.140.141
          ansible_user: dancu
          vpn_ip: 10.1.0.3
  vars:
    wg_port: 51820
    vpn_subnet: 10.1.0.0/24
       