global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['10.0.0.5:9100', '10.0.0.6:9100', '10.0.0.7:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['10.0.0.5:18080', '10.0.0.6:18080', '10.0.0.7:18080']