- name: Update and upgrade system packages
  ansible.builtin.apt:
    upgrade: yes
  register: result
  retries: 5
  delay: 30
  until: result is succeeded
  
- name: Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_flag

- name: Reboot the VM
  ansible.builtin.reboot:
    msg: "Reboot the vm from ansible"
  when: reboot_flag.stat.exists
